apiVersion: v1
kind: Secret
metadata:
  name: grover-secrets
  namespace: grover
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production"
  PAYPAL_CLIENT_ID: ""
  PAYPAL_CLIENT_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  RABBITMQ_DEFAULT_USER: "grover"
  RABBITMQ_DEFAULT_PASS: "grover123"
